services:
  # Servicio principal que ejecuta Bacula con Bacularis Director, Storage Daemon y Web UI
  bacularis:
    image: bacularis/bacularis-standalone:5.2.0-alpine  # Imagen con Bacula + Bacularis
    container_name: bacula
    ports:
      - "9097:9097"  # Acceso a la interfaz web de Bacularis
      - "9103:9103"  # Puerto del Storage Daemon (SD)
    volumes:
      # Base de datos del catálogo interno de Bacula
      - bacularis_catalog:/var/lib/postgresql/data
      # Configuración de Bacula Director, SD y FD
      - ./data/bacula/config:/etc/bacula
      # Datos gestionados por Bacula (backup jobs, estado de ejecución, etc.)
      - bacularis_data:/var/lib/bacula
      # Configuración específica del API de Bacularis
      - bacularis_api_config:/var/www/bacularis/protected/vendor/bacularis/bacularis-api/API/Config
      # Logs del API de Bacularis
      - bacularis_api_logs:/var/www/bacularis/protected/vendor/bacularis/bacularis-api/API/Logs
      # Configuración de la interfaz web de Bacularis
      - bacularis_web_config:/var/www/bacularis/protected/vendor/bacularis/bacularis-web/Web/Config
      # Logs de la interfaz web
      - bacularis_web_logs:/var/www/bacularis/protected/vendor/bacularis/bacularis-web/Web/Logs
      # Directorio donde se almacenan los backups (host)
      - ./backups:/var/lib/bacula/archive
      # Se monta los certificados
      - ./ssl:/etc/ssl
      # Se carga la configuración de Bacularis
      - ./data/bacula/bacularis-nginx.conf:/etc/nginx/http.d/bacularis-nginx.conf
    restart: unless-stopped
    environment:
      TZ: America/Guayaquil  # Define zona horaria del contenedor

  # Servicio de base de datos PostgreSQL
  postgres:
    image: postgres:17  # Imagen oficial de PostgreSQL versión 17
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}         # Usuario definido en .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Contraseña definida en .env
      POSTGRES_DB: ${POSTGRES_DB}             # Base de datos inicial
      TZ: America/Guayaquil                   # Zona horaria
    ports:
      - "5432:5432"  # Puerto estándar de PostgreSQL
    volumes:
      - ./data/postgres:/var/lib/postgresql/data  # Persistencia de la base de datos
    restart: unless-stopped

  # Servicio de Grafana para monitoreo, conectado a la base de datos PostgreSQL
  grafana:
    image: grafana/grafana:12.0.1  # Imagen oficial de Grafana
    container_name: grafana
    ports:
      - "3000:3000"  # Puerto de acceso a la interfaz web de Grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}          # Usuario administrador definido en .env
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}  # Contraseña definida en .env
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_FILE=/etc/grafana/certs/sistema.crt
      - GF_SERVER_CERT_KEY=/etc/grafana/certs/sistema.key
    volumes:
      - ./data/grafana:/var/lib/grafana  # Persistencia de datos y configuraciones de dashboards
      - ./ssl:/etc/grafana/certs # Certificado para conexion https
    depends_on:
      - postgres  # Espera a que PostgreSQL esté listo
    restart: unless-stopped

volumes:
  # Volúmenes para la persistencia de Bacula y Bacularis
  bacularis_catalog:
  bacularis_data:
  bacularis_api_config:
  bacularis_api_logs:
  bacularis_web_config:
  bacularis_web_logs:
